# Generated by Django 3.2 on 2021-05-03 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.AutoField(help_text='Код книги', primary_key=True, serialize=False),
        ),
    ]
